function y = FastHankelCircVec(c,x)
% FASTHANKELCIRCVEC  Fast application of Hankel matrix.
%   y = FASTHANKELCIRCVEC(c,x) applies Hankel matrix generated by c been
%   the first column to vectors x. y returns the matrix vector product
%   y = Hx, where H is a Hankel matrix generated by c and r,
%       -                                  -
%       |  c1    c2    c3  ...  cn-1   cn  |
%       |  c2    c3    c4  ...   cn    c1  |
%   C = |  c3    c4    c5  ...   c1    c2  | .
%       | ...   ...   ...  ...  ...   ...  |
%       | cn-1   cn    c1  ...  cn-3  cn-2 |
%       |  cn    c1    c2  ...  cn-2  cn-1 |
%       -                                  -
%
%   See also FASTCIRCULANTVEC, FASTHANKELVEC.

%   Copyright (c) 2015 Yingzhou Li, Stanford University

y = flipud(ifft(fft(flipud(c)).*fft(x)));

end